language: c

os:
 - linux
 - osx

env:
 - EXTRALIBS=""
 - EXTRALIBS="libusb-dev"
 - EXTRALIBS="libusb-1.0-0-dev libgd2-xpm-dev"

before_install:
 - sh .travis-before-install $EXTRALIBS

compiler:
 - clang
 - gcc

script:
 - PATH=/usr/local/opt/gettext/bin:$PATH autoreconf -i -f
 - ./configure && make && make check

notifications:
  email:
    on_success: change
    on_failure: always
