language: c

os:
 - linux
 - osx

env:
 - EXTRALIBS=""
 - EXTRALIBS="libusb-dev"
 - EXTRALIBS="libusb-1.0-0-dev libgd-dev"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install autopoint $EXTRALIBS

compiler:
 - clang
 - gcc

script:
 - autoreconf -i -f
 - ./configure && make && make check

notifications:
  recipient:
   - marcus@jet.franken.de
  email:
    on_success: change
    on_failure: always
