language: c

os:
 - linux
 - osx

env:
 - EXTRALIBS=""
 - EXTRALIBS="libusb-dev"
 - EXTRALIBS="libusb-1.0-0-dev libgd2-xpm-dev"

before_install:
 - sudo apt-get update -qq || brew update
 - sudo apt-get install autopoint $EXTRALIBS || brew install gettext

compiler:
 - clang
 - gcc

script:
 - export PATH=/usr/local/opt/gettext/bin:$PATH:. autoreconf -i -f
 - ./configure && make && make check

notifications:
  recipient:
   - marcus@jet.franken.de
  email:
    on_success: change
    on_failure: always
