language: c

os:
 - linux
 - osx

compiler:
 - clang
 - gcc

script:
 - aclocal --force -I gphoto-m4
 - libtoolize --copy --force
 - autoconf
 - autoheader
 - automake --add-missing --copy --force-missing
 - ./configure && make && make test

notifications:
  recipient:
   - marcus@jet.franken.de
  email:
    on_success: change
    on_failure: always
