language: c

os:
 - linux
 - osx

compiler:
 - clang
 - gcc

script:
 - autoreconf -i -f
 - ./configure && make && make test

notifications:
  recipient:
   - marcus@jet.franken.de
  email:
    on_success: change
    on_failure: always
