language: c

os:
 - linux
 - osx

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install autopoint

compiler:
 - clang
 - gcc

script:
 - autoreconf -i -f
 - ./configure && make && make test

notifications:
  recipient:
   - marcus@jet.franken.de
  email:
    on_success: change
    on_failure: always
